Add Notification Feature
Dirakit/Dirakit-Admin pull request #5
Opened 2017-01-25 04:37 UTC by fauzan-ngantuk

7e0be7805f5dfdca3e945d7ce7fde8f7b8c6868b @sendz

2017-01-25 04:43 UTC, sendz commented on assets/custom.js
> +	$(document).ready(function(){
@fauzan-ngantuk `$(document).ready()` dipanggil sekali aja di satu file js, jangan 3 kali begini...

2017-01-25 04:44 UTC, sendz commented on assets/custom.js
> +	$(document).ready(function(){
pindahin isinya ke yang atas.

2017-01-25 04:45 UTC, sendz requested changes
rapihin custom.js, cuma boleh ada satu `$(document).ready()`.

2017-01-25 05:24 UTC, fauzan-ngantuk commented
@sendz kayak gini bukan --- > 5c5948f81f99f4e4e79a4a814c56276745368136

2017-01-25 05:26 UTC, fauzan-ngantuk commented
@sendz kayak gini ? ----->5c5948f81f99f4e4e79a4a814c56276745368136

2017-01-25 05:27 UTC, fauzan-ngantuk commented on assets/custom.js
> +	$(document).ready(function(){
@sendz kayak gini bukan ? ---- >5c5948f81f99f4e4e79a4a814c56276745368136

2017-01-25 05:27 UTC, fauzan-ngantuk commented
5c5948f81f99f4e4e79a4a814c56276745368136

2017-01-25 06:35 UTC, sendz commented
kenapa nyimpen `$(window).ready()` di dalam function? kalau function itu mau dipanggil sama element lain gak perlu tambahin `$(window).ready()`.

`$(window).ready()` cuma dipake sekali buat script yang dibutuhkan tapi gak akan dipanggil di external, cuma buat inisialisasi aja.

2017-01-25 12:16 UTC, sendz commented on assets/custom.js
>  function activate_dropdown() {
this implementation is so wrong, bro... if you want to declare a function, don't trigger it when window is ready. instead, if you want the code triggered when your window is ready, don't declare it as a function.

2017-01-25 12:20 UTC, sendz commented on assets/custom.js
> +		$('#project_filter').click(function(){
and, you don't need to use `click` listener here as the code below `$('#project_filter').dropdown();` means element with id `project_filter` will have `dropdown` 'feature'.

2017-01-25 12:22 UTC, sendz commented on assets/custom.js
>  function activate_dropdown() {
what I understand from your code is, you are trying to assign any object to have dropdown, so remove function declaration lines instead.

2017-01-25 12:24 UTC, sendz commented on assets/custom.js
> +			$('#feed1').dropdown();
add a class to any object which decided to have dropdown and initiate your dropdown using a class.

example `$('.with-dropdown').dropdown()` so any classes with `.with-dropdown` will have dropdown feature.

2017-01-25 12:37 UTC, sendz commented on assets/custom.js
>  function activate_dropdown() {
simplify your code to this one

```$(document).ready(function(){
	$('.ui.sidebar').sidebar('toggle');
	$('.dropdown').dropdown();
});```

add class `dropdown` to `#project_filter`, `#feed1` and `#feed2`

2017-01-27 21:15 UTC, fauzan-ngantuk commented
@sendz maybe i have to learn the concept first , itu kemaren hasil dari coba-coba awkawk

2020-04-04 05:19 UTC, closed without merging